/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package space.nixus.userbuilder;

import space.nixus.userbuilder.builder.UserBuilder;
import space.nixus.userbuilder.model.IUser;

public class App {

    public static void main(String[] args) {
        new App().run();
    }

    public void run() {
        System.out.println(getUser().toString());
    }

    public IUser getUser() {
        return new UserBuilder()
        .setUserName("Batman")
        .setEmail("batman@bat.cave")
        .setDisplayName("Bruce Wayne")
        .create();
    }
}
