/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package space.nixus.maddoc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GameTest {
    @Test void appHasAGreeting() {
        Game classUnderTest = new Game();
        //assertNotNull(classUnderTest., "app should have a greeting");
    }
}
